### ISSUE TITLE
コードラビットの設定

### ISSUE THREAD

**Issue by centmount1** [AIIT-Oikawa-PBL-2024/TeamTask#12]

**Comment by sayzkkgw** [comment]
coderabit いじってたら早々にレートリミットに引っかかり、、、短いサンプルコードのレビューしかさせてないのに。。


![Image](https://github.com/AIIT-Oikawa-PBL-2024/TeamTask/assets/56593880/f77b4950-547d-48d4-90f9-7a64255b8123)

**Comment by sayzkkgw** [comment]
test
